# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2025-07-15 15:58:57.428634 UTC
# Namespace:     voltbro.foc

from voltbro.foc.command_1_0 import command_1_0 as command_1_0
from voltbro.foc.specific_control_1_0 import specific_control_1_0 as specific_control_1_0

# Convenience aliases of the newest minor versions known at the time of code generation.
command_1 = command_1_0
specific_control_1 = specific_control_1_0
