# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /Users/igor/Work/misc/cyphal_ws/types/voltbro/foc/command.1.0.dsdl
#
# Generated at:  2025-07-15 15:58:57.429324 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     voltbro.foc.command
# Version:       1.0
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import uavcan.primitive.scalar
import uavcan.si.unit.angle
import uavcan.si.unit.angular_velocity
import uavcan.si.unit.torque

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class command_1_0:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 torque:      None | uavcan.si.unit.torque.Scalar_1_0 = None,
                 angle:       None | uavcan.si.unit.angle.Scalar_1_0 = None,
                 velocity:    None | uavcan.si.unit.angular_velocity.Scalar_1_0 = None,
                 angle_kp:    None | uavcan.primitive.scalar.Real32_1_0 = None,
                 velocity_kp: None | uavcan.primitive.scalar.Real32_1_0 = None) -> None:
        """
        voltbro.foc.command.1.0
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param torque:      uavcan.si.unit.torque.Scalar.1.0 torque
        :param angle:       uavcan.si.unit.angle.Scalar.1.0 angle
        :param velocity:    uavcan.si.unit.angular_velocity.Scalar.1.0 velocity
        :param angle_kp:    uavcan.primitive.scalar.Real32.1.0 angle_kp
        :param velocity_kp: uavcan.primitive.scalar.Real32.1.0 velocity_kp
        """
        self._torque:      uavcan.si.unit.torque.Scalar_1_0
        self._angle:       uavcan.si.unit.angle.Scalar_1_0
        self._velocity:    uavcan.si.unit.angular_velocity.Scalar_1_0
        self._angle_kp:    uavcan.primitive.scalar.Real32_1_0
        self._velocity_kp: uavcan.primitive.scalar.Real32_1_0

        if torque is None:
            self.torque = uavcan.si.unit.torque.Scalar_1_0()
        elif isinstance(torque, uavcan.si.unit.torque.Scalar_1_0):
            self.torque = torque
        else:
            raise ValueError(f'torque: expected uavcan.si.unit.torque.Scalar_1_0 '
                             f'got {type(torque).__name__}')

        if angle is None:
            self.angle = uavcan.si.unit.angle.Scalar_1_0()
        elif isinstance(angle, uavcan.si.unit.angle.Scalar_1_0):
            self.angle = angle
        else:
            raise ValueError(f'angle: expected uavcan.si.unit.angle.Scalar_1_0 '
                             f'got {type(angle).__name__}')

        if velocity is None:
            self.velocity = uavcan.si.unit.angular_velocity.Scalar_1_0()
        elif isinstance(velocity, uavcan.si.unit.angular_velocity.Scalar_1_0):
            self.velocity = velocity
        else:
            raise ValueError(f'velocity: expected uavcan.si.unit.angular_velocity.Scalar_1_0 '
                             f'got {type(velocity).__name__}')

        if angle_kp is None:
            self.angle_kp = uavcan.primitive.scalar.Real32_1_0()
        elif isinstance(angle_kp, uavcan.primitive.scalar.Real32_1_0):
            self.angle_kp = angle_kp
        else:
            raise ValueError(f'angle_kp: expected uavcan.primitive.scalar.Real32_1_0 '
                             f'got {type(angle_kp).__name__}')

        if velocity_kp is None:
            self.velocity_kp = uavcan.primitive.scalar.Real32_1_0()
        elif isinstance(velocity_kp, uavcan.primitive.scalar.Real32_1_0):
            self.velocity_kp = velocity_kp
        else:
            raise ValueError(f'velocity_kp: expected uavcan.primitive.scalar.Real32_1_0 '
                             f'got {type(velocity_kp).__name__}')

    @property
    def torque(self) -> uavcan.si.unit.torque.Scalar_1_0:
        """
        uavcan.si.unit.torque.Scalar.1.0 torque
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._torque

    @torque.setter
    def torque(self, x: uavcan.si.unit.torque.Scalar_1_0) -> None:
        if isinstance(x, uavcan.si.unit.torque.Scalar_1_0):
            self._torque = x
        else:
            raise ValueError(f'torque: expected uavcan.si.unit.torque.Scalar_1_0 got {type(x).__name__}')

    @property
    def angle(self) -> uavcan.si.unit.angle.Scalar_1_0:
        """
        uavcan.si.unit.angle.Scalar.1.0 angle
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._angle

    @angle.setter
    def angle(self, x: uavcan.si.unit.angle.Scalar_1_0) -> None:
        if isinstance(x, uavcan.si.unit.angle.Scalar_1_0):
            self._angle = x
        else:
            raise ValueError(f'angle: expected uavcan.si.unit.angle.Scalar_1_0 got {type(x).__name__}')

    @property
    def velocity(self) -> uavcan.si.unit.angular_velocity.Scalar_1_0:
        """
        uavcan.si.unit.angular_velocity.Scalar.1.0 velocity
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._velocity

    @velocity.setter
    def velocity(self, x: uavcan.si.unit.angular_velocity.Scalar_1_0) -> None:
        if isinstance(x, uavcan.si.unit.angular_velocity.Scalar_1_0):
            self._velocity = x
        else:
            raise ValueError(f'velocity: expected uavcan.si.unit.angular_velocity.Scalar_1_0 got {type(x).__name__}')

    @property
    def angle_kp(self) -> uavcan.primitive.scalar.Real32_1_0:
        """
        uavcan.primitive.scalar.Real32.1.0 angle_kp
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._angle_kp

    @angle_kp.setter
    def angle_kp(self, x: uavcan.primitive.scalar.Real32_1_0) -> None:
        if isinstance(x, uavcan.primitive.scalar.Real32_1_0):
            self._angle_kp = x
        else:
            raise ValueError(f'angle_kp: expected uavcan.primitive.scalar.Real32_1_0 got {type(x).__name__}')

    @property
    def velocity_kp(self) -> uavcan.primitive.scalar.Real32_1_0:
        """
        uavcan.primitive.scalar.Real32.1.0 velocity_kp
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._velocity_kp

    @velocity_kp.setter
    def velocity_kp(self, x: uavcan.primitive.scalar.Real32_1_0) -> None:
        if isinstance(x, uavcan.primitive.scalar.Real32_1_0):
            self._velocity_kp = x
        else:
            raise ValueError(f'velocity_kp: expected uavcan.primitive.scalar.Real32_1_0 got {type(x).__name__}')

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Serializer_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.pad_to_alignment(8)
        self.torque._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.angle._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.velocity._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.angle_kp._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.velocity_kp._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        assert 160 <= (_ser_.current_bit_length - _base_offset_) <= 160, \
            'Bad serialization of voltbro.foc.command.1.0'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Deserializer_) -> command_1_0:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "torque"
        _des_.pad_to_alignment(8)
        _f0_ = uavcan.si.unit.torque.Scalar_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f1_ holds the value of "angle"
        _des_.pad_to_alignment(8)
        _f1_ = uavcan.si.unit.angle.Scalar_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f2_ holds the value of "velocity"
        _des_.pad_to_alignment(8)
        _f2_ = uavcan.si.unit.angular_velocity.Scalar_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f3_ holds the value of "angle_kp"
        _des_.pad_to_alignment(8)
        _f3_ = uavcan.primitive.scalar.Real32_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f4_ holds the value of "velocity_kp"
        _des_.pad_to_alignment(8)
        _f4_ = uavcan.primitive.scalar.Real32_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        self = command_1_0(
            torque=_f0_,
            angle=_f1_,
            velocity=_f2_,
            angle_kp=_f3_,
            velocity_kp=_f4_)
        _des_.pad_to_alignment(8)
        assert 160 <= (_des_.consumed_bit_length - _base_offset_) <= 160, \
            'Bad deserialization of voltbro.foc.command.1.0'
        assert isinstance(self, command_1_0)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'torque=%s' % self.torque,
            'angle=%s' % self.angle,
            'velocity=%s' % self.velocity,
            'angle_kp=%s' % self.angle_kp,
            'velocity_kp=%s' % self.velocity_kp,
        ])
        return f'voltbro.foc.command.1.0({_o_0_})'

    _EXTENT_BYTES_ = 20

    # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
    # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
    # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
    # is not dependent on PyDSDL.
    _MODEL_: _pydsdl_.StructureType = _restore_constant_(
        'ABzY8!FqOR0{_)k-D@316u+(cY|@$#KR`>p`Vb?vyG^T!h(c*K6s}Fvq*hSEWOjFQ&(OU)+nw1oS16>QrI8VZOrLz|yN`-beezH6'
        'vEn}=_#Dsd?ET116QiU;FNDmVbLPxBzw<jYXQS`IqvMt0r(a8(k&I%GNS1LL^Dk)-GmnI#kqXHbGy3?F%JNX<8N1$0nb|UL-8Fa2'
        'l<p@9ZJ>T)O~fk5gtsa}5BD`_5*a;2)>tOFNDNf;;Ei&<Wok!im3!u{(IbQ^mGK}~Oqyl%w?`yxE2I18IE$lB1jk536(!1s1xK9_'
        '`t`}2u7x!5B=_=!D^H2+R?fVokj6AKFbKn~AYgRaz*xC)Vy_6&j5oOAYZ$@sTr8;CiNgp9xFRu2>IzJ)icy7BD$)=UMs-rZw9wja'
        'w|SRPcg3m@iptk!(dZY5R0tW(qHag`(NBZcG5$QV2d`!{R0yF&Xy?i``uJwN(*4`s-mcV++(Wl{fJlrc?6wjKX)whyqx(oCLZd6F'
        'q<W$Ye-boZG4B}g;1!8EMJ&x&NEM6BranPd`8tb8Dl$cQWajlaks{ARhKiVxlw!pCg#8!uz$39htTE^Xq|o|;Rc;ww_di8krO)dk'
        '^FI^WO~1iq=!eY|XiRQP-_}w3X&%HpBpIvcu|2+1W9hrX`jY#$u)Zs-?+WWpduKgcK2xANL4ZmOEMtkX^<3j2Gn?SUSv^+d>L{L|'
        '+R<;oIXC*K<Or2Lz~}*Y1TISUF#U3oEm4AGLa4%(Oes2t_w?n%O3~%eM}ipZJ=vmVhaQ-b>isr)^deWE6yHnuSrSw~M?`9LbuTBf'
        '*$4!NgOFWe4S}S$)Vi9ojAHT~nh%f=ICdXg)z2@`DB?+dml0gI+W9<2sG7Z6^sq)_1oJyHRjYn41H2<r=g8EC@&MCq@WgfyF6g>l'
        '4B9S2jO^}XgsrDEDXx+EJdi=b@K%9rVNuZT<*w`C)t>8sCiVCLw*j0gSFhKq@CHo6oA+S~PVe7v0~w7tmd}MlVHz7sK_cP&CcHBb'
        '?;=N554{bFgr3+1@Ik?N_;62x_ZOSH_zfQ&I*;Kp)Cw$N9<H^Ca-+Ta+$on^yZ~b904s<)#lHY`QK#Z%#QPL{a(BToz6>8EyqCCY'
        'KBd}^yV?_^J$6<o@D=Q)!4L4Dn+CU@1`T$k`5zfE*6Zh4BF9iW=zaKcs^mxeUH7CzYLU_S{JF#CMZdfCz}GV$uj9iVH>;U_TqQm|'
        'cEG6eM6o&|`hN9`Gt)D(v$N->XWp)!ZY`Hhi$cG`qizcEL!(d|3Ev^%J0uQ5o#C$OXu$2pMTz7yK$zk-Ave?Ag!u*4BP~94ESN3D'
        '6fhVE4Xf}Id<&1^XZQnt&%0`K@nAWZqqC2rvtN$R`+z=Jn&X?kY6rQ&*0k+#KJ%~6JP?@Iy598{FNwqsgvk>J1U>BL1Dv<)IQ0+S'
        '{&a`_^?zC}?!g53ib*TIfYJ*cY0J1r{G&5oLFvkF;~w#E&Ugc*8@r8r#HH~=ls?>Tyi;u1>-`P*WodfH4FCW'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
