# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2025-07-15 15:58:57.405025 UTC
# Namespace:     voltbro.config

# There are no data types in this namespace. There may be data types in nested namespaces.
