# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2025-07-15 15:58:57.397649 UTC
# Namespace:     voltbro.freeflyer

# There are no data types in this namespace. There may be data types in nested namespaces.
